title: Joshua Valluru # your name (or website title) here
logo: "/logo.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Senior at The Harker Upper School
  <br>
  Email: 20joshv@students.harker.org
  <br><br>
  <a href="https://joshuavalluru.github.io/#music-portfolio">Music Portfolio</a>
  <br>
  <a href="https://joshuavalluru.github.io/#computer-programming-background">Computer Programming Background</a>
  <br>
  <a href="https://joshuavalluru.github.io/#research-project-under-researcher-lakkarajus-stanford-harvard">Research Project under Researcher Lakkaraju (Stanford/ Harvard)</a>
  <br>
  <a href="https://joshuavalluru.github.io/#audiovideo-software-toolsapplications">Audio/Video Software Tools/Applications</a>
  <br>
  <a href="https://joshuavalluru.github.io/#salvationpc">SalvationPC</a>
  <br>
  <a href="https://joshuavalluru.github.io/#ai-club-presentations">AI Club Presentations</a>
  <br><br>
  <a href="https://www.linkedin.com/in/joshua-valluru-4977b5192">View My LinkedIn Profile</a>
  
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
