title:   Joshua Valluru # your name (or website title) here
logo: "/logo.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Computer Science @UPenn
  <br>
  jvalluru@sas.upenn.edu
  <br><br>
  <br><a href="https://joshuavalluru.github.io/#computer-programming">Computer Programming</a>
  <br><a href="https://joshuavalluru.github.io/#research-projects-under-himabindu-lakkaraju-stanford-harvard">Research Projects</a>
  <br><a href="https://joshuavalluru.github.io/#salvationpc">SalvationPC</a>
  <br><a href="https://joshuavalluru.github.io/#music-portfolio">Music Portfolio</a>
  <br>
  <a href="https://www.linkedin.com/in/joshua-valluru-4977b5192">View My LinkedIn Profile</a>
  <br><br>
  <br><br>
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-151433000-1 # your Google Analytics tracking ID here
